#!/usr/bin/env bash
# Handling DNS
if [ $# -eq 2 ]; then
	record=$(dig $2.$1 | awk '/^;; ANSWER SECTION:/ {getline; print $4}')
	info=$(dig $2.$1 | awk '/^;; ANSWER SECTION:/ {getline; print $5}')
	echo "The subdomain $2 is a ${record} record and points to ${info}"
elif [ $# -eq 1 ]; then
	declare subdomains=("www" "lb-01" "web-01" "web-02")
	for arg in "${subdomains[@]}";
	do
		record=$(dig ${arg}.$1 | awk '/^;; ANSWER SECTION:/ {getline; print $4}')
		info=$(dig ${arg}.$1 | awk '/^;; ANSWER SECTION:/ {getline; print $5}')
		echo "The subdomain ${arg} is a ${type} record and points to ${info}"
	done
fi
