#!/usr/bin/env bash
# Handling DNS
function subdomain_info {
	local domain=$1
	local subdomain=$2
	if [ $# -eq 2 ]; then
		local type=$(dig ${subdomain}.${domain} | awk '/^;; ANSWER SECTION:/ {getline; print $4}')
		local info=$(dig ${subdomain}.${domain} | awk '/^;; ANSWER SECTION:/ {getline; print $5}')
		echo "The subdomain ${subdomain} is a ${type} record and points to ${info}"
	elif [ $# -eq 1 ]; then
		declare subdomains=("www" "lb-01" "web-01" "web-02")
		for arg in "${subdomains[@]}";
		do
			local type=$(dig ${arg}.${domain} | awk '/^;; ANSWER SECTION:/ {getline; print $4}')
			local info=$(dig ${arg}.${domain} | awk '/^;; ANSWER SECTION:/ {getline; print $5}')
			echo "The subdomain ${arg} is a ${type} record and points to ${info}"
		done
	fi
}
