#!/usr/bin/env bash
#This is a command to display numbers from 1 to 100 along incorporating statements
i=1
while [ $i -lt 101 ]
do
	if [ $i % 3 == 0 ]
	then
		echo "Fizz"
	elif [ $i % 5 == 0 ]
	then
		echo "Buzz"
	elif [ $i % 3 == 0 && $i % 5 == 0 ]
		echo "FizzBuzz"
	else
		echo $i
	fi
	(( i++ ))
done
