#!/usr/bin/env bash
#This is a command to display sentences using while loop and if statements
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best school"
	fi
	(( i++ ))
done
