#!/usr/bin/env bash
#This is a command to dispaly numbers from 1 to 20 and incorporate statements along the way
i=1
while [ $i -lt 21 ]
do
	if [ $i -eq 4 ]
	then
		echo $i
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo $i
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo $i
		echo "bad luck from Italy"
	else
		echo $i
	fi
	(( i++ ))
done
