#!/usr/bin/env bash
#This is a command to dispaly numbers from 1 to 20 and incorporate statements along the way
i=0
while [ $i -lt 20 ]
do
	case "$i" in
		"4")
		echo "bad luck from China"
		;;
	"9")
		echo "bad luck from Japan"
		;;
	"17")
		echo "bad luck from Italy"
		;;
esac
	(( i++ ))
	echo $i
done
