#!/usr/bin/env bash
#Script to run nginx server as nginx
sudo sed -i 's/www-data;/nginx;/g' /etc/nginx/nginx.conf
chmod 444 /etc/nginx/nginx.conf
pkill apache
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
